# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 20:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0015_sensordata_software_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensordatavalue',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='sensordatavalue',
            unique_together=set([('sensordata', 'value_type')]),
        ),
    ]
